<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="CGGDESKFF05" name="com.cgg.testcases.SWLoginTest" tests="4" failures="1" timestamp="23 Oct 2017 07:07:33 GMT" time="186.056" errors="0">
  <testcase name="testLogin" time="61.100" classname="com.cgg.testcases.SWLoginTest"/>
  <testcase name="testLogin" time="2.552" classname="com.cgg.testcases.SWLoginTest">
    <failure type="java.lang.AssertionError" message="unable to logged for valid data">
      <![CDATA[java.lang.AssertionError: unable to logged for valid data
	at org.testng.Assert.fail(Assert.java:94)
	at com.cgg.testcases.TestBase.reportFail(TestBase.java:457)
	at com.cgg.testcases.SWLoginTest.testLogin(SWLoginTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- testLogin -->
  <testcase name="testLogin" time="61.197" classname="com.cgg.testcases.SWLoginTest"/>
  <testcase name="testLogin" time="61.207" classname="com.cgg.testcases.SWLoginTest"/>
</testsuite> <!-- com.cgg.testcases.SWLoginTest -->
